## 1. 导入数据及预处理

In [5]:
import pandas as pd
content = pd.read_csv('D:/Machine Learning/NLP/data/sqlResult_1558435.csv',encoding='gb18030')

In [6]:
content = content.fillna('')

In [3]:
content[content['source'].str.contains('新华')]

id            author source  \
3      89614                      新华社   
17     89600                      新华网   
25     89592                      新华网   
27     89590                      新华网   
39     89578                      新华社   
51     89566                      新华网   
65     89552                     新华社@   
95     89522                      新华社   
104    89513                      新华网   
113    89504                      新华社   
231    89386                      新华网   
305    89312                      新华社   
312    89305                      新华社   
314    89303                      新华社   
329    89288                      新华网   
330    89287                      新华网   
331    89286                      新华网   
335    89282                      新华网   
365    89252                      新华网   
376    89241                      新华网   
388    89229                      新华网   
445    89172                      新华网   
446    89171                      新华网   
448    89169                      新华网   
511    89106                      新华网   
514    89103                      新华网   
541    89076          王璐 PS039  新华通讯社   
543    89074               刘瑞莹    新华社   
545    89072                      新华社   
552    89065                      新华网   
...      ...               ...    ...   
89581     30       INACIO ROSA    新华社   
89582     29       INACIO ROSA    新华社   
89583     28       INACIO ROSA    新华社   
89584     27       INACIO ROSA    新华社   
89585     26       INACIO ROSA    新华社   
89586     25       INACIO ROSA    新华社   
89587     24      LOVELY GHOSH    新华社   
89588     23      LOVELY GHOSH    新华社   
89589     22      LOVELY GHOSH    新华社   
89590     21      LOVELY GHOSH    新华社   
89591     20      LOVELY GHOSH    新华社   
89592     19                张旌    新华社   
89593     18                      新华社   
89594     17  LISELOTTE SABROE    新华社   
89595     16  LISELOTTE SABROE    新华社   
89596     15  LISELOTTE SABROE    新华社   
89597     14  LISELOTTE SABROE    新华社   
89598     13  LISELOTTE SABROE    新华社   
89599     12  LISELOTTE SABROE    新华社   
89600     11  LISELOTTE SABROE    新华社   
89601     10  LISELOTTE SABROE    新华社   
89602      9  LISELOTTE SABROE    新华社   
89603      8               郑焕松    新华社   
89604      7               郑焕松    新华社   
89605      6               郑焕松    新华社   
89606      5                邹峥    新华社   
89607      4                王衡    新华社   
89608      3                张旌    新华社   
89609      2               夏文辉    新华社   
89610      1            王子江 张寒    新华社   

                                                 content  \
3        这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
17     国歌法草案首次提请最高立法机关审议\r\n点击图片进入下一页\r\n新闻：十二届全国人大常委...   
25     当地时间2017年6月17日，土耳其马尼萨省，在土耳其第1步兵训练大队司令部军营，590名土...   
27     英国与欧盟的“脱欧”谈判于19日正式开始。然而此时，英国首相特雷莎·梅正面临着空前的政治压力...   
39       这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
51     戈壁的大漠黄沙曾掩埋了无数西域古道，而如今一条大漠天路正顽强地与黄沙“搏斗”，在乌兰布和、腾...   
65     从百度、支付宝到App?“高考志愿填报”五花八门\r\n顾女士近来减少了刷朋友圈的频率，一有...   
95     新华社韩国济州6月18日电综述：亚投行第二届年会三大亮点\r\n新华社记者 耿学鹏 严蕾\r...   
104    粤港澳概念板块午后走强，珠海港、恒基达鑫、白云机场等个股的午后纷纷快速拉升。\r\n据悉，首...   
113    新华社北京6月18日电 经军委领导批准，《军营理论热点怎么看·2017》日前印发全军。\r\...   
231    东方卫视明星旅游体验综艺节目《旅途的花样》6月17日（周六）晚播出了第三期节目。本周，“花样...   
305    新华社兰州6月19日电（记者张钦）记者19日了解到，刚刚出台的《甘肃省网络扶贫行动的实施方案...   
312    新华社乌鲁木齐6月18日电（记者杜刚、王秉阳）6月18日，新疆天山天池首次举办山地马拉松比赛...   
314    新华社北京6月19日电（记者熊丰）记者从公安部消防局获悉，19日上午6时，由公安部消防局组织...   
329    新华社北京６月２３日电（记者邢静）幸福是人们对生活最美好的期待，２０１７年哪些城市生活更幸福...   
330    新华社昆明6月23日电（记者王研）近年来，随着云南航空业的迅速发展，机场禁毒形势也日益严峻。...   
331    新华社北京６月２３日电（记者倪元锦）２１日起，京津冀迎来今年以来最强降雨。记者采访气象专家，...   
335    新华社北京６月２３日电（记者 倪元锦）２１日起，京津冀迎来今年以来最强降雨。记者采访气象专家...   
365    新华社哈尔滨6月23日电（记者 许正）记者23日从黑龙江省环保厅获悉，这个省目前建立的自然保...   
376    新华社合肥６月２３日电? 题：安徽不断将跨省流域补偿试点推向深入\r\n新华社记者杨丁淼\r...   
388    新华社重庆６月２３日电? 题：“悟空”为何跌下共享风口？——重庆首家共享单车“退市”观察\r...   
445    新华社贵阳６月２３日电（记者 李黔渝）贵州省政府近日下发通知，对严重影响公共安全的中学、医院...   
446    新华社广州6月23日电 题：激发内生动力 走在脱贫路上——广东探索东西部扶贫协作新路径\r\...   
448    新华社南京6月23日电（记者 朱国亮）2

In [7]:
import numpy as np

In [8]:
content['is_xinhua'] = np.where(content['source'].str.contains('新华'),1,0)

In [7]:
content.head()

id      author                  source  \
0  89617              快科技@http://www.kkj.cn/   
1  89616              快科技@http://www.kkj.cn/   
2  89615              快科技@http://www.kkj.cn/   
3  89614                                 新华社   
4  89613  胡淑丽_MN7479                   深圳大件事   

                                             content  \
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3    这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   

                                             feature  \
0  {"type":"科技","site":"cnbeta","commentNum":"37"...   
1  {"type":"科技","site":"cnbeta","commentNum":"15"...   
2  {"type":"科技","site":"cnbeta","commentNum":"18"...   
3  {"type":"国际新闻","site":"环球","commentNum":"0","j...   
4  {"type":"新闻","site":"网易热门","commentNum":"978",...   

                           title  \
0           小米MIUI 9首批机型曝光：共计15款   
1     骁龙835在Windows 10上的性能表现有望改善   
2      一加手机5细节曝光：3300mAh、充半小时用1天   
3  葡森林火灾造成至少62人死亡 政府宣布进入紧急状态（组图）   
4       44岁女子约网友被拒暴雨中裸奔 交警为其披衣相随   

                                                 url  is_xinhua  
0     http://www.cnbeta.com/articles/tech/623597.htm          0  
1     http://www.cnbeta.com/articles/tech/623599.htm          0  
2     http://www.cnbeta.com/articles/tech/623601.htm          0  
3  http://world.huanqiu.com/hot/2017-06/10866126....          1  
4  http://news.163.com/17/0618/00/CN617P3Q0001875...          0

In [9]:
import jieba

In [10]:
def cut(string):return ' '.join(jieba.cut(string))

In [11]:
content['title'] = content['title'].apply(cut)

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
Loading model cost 1.860 seconds.
Prefix dict has been built succesfully.


In [19]:
content['title'][:10]

0                  小米 MIUI   9 首批 机型 曝光 ： 共计 15 款
1           骁龙 835 在 Windows   10 上 的 性能 表现 有望 改善
2           一加 手机 5 细节 曝光 ： 3300mAh 、 充 半小时 用 1 天
3    葡 森林 火灾 造成 至少 62 人 死亡   政府 宣布 进入 紧急状态 （ 组图 ）
4         44 岁 女子 约 网友 被 拒 暴雨 中 裸奔   交警 为 其 披衣 相随
5                             金融股 一枝独秀   配置 价值 犹存
6                    配骁龙 660   全面 屏 鼻祖 夏普 新机 酝酿 中
7                          博友 早评 ： 震荡 有利 消化 套牢 筹码
8              武汉 千余 警察 出动   抓获 808 名 俊男靓女 全是 诈骗犯
9                     纳入 MSCI 指数   A股 长期 配置 价值 提升
Name: title, dtype: object

In [20]:
len(content)

89611

In [12]:
content = content.sample(n=5000)

In [13]:
xinhuashe_news = content[content['source'].str.contains('新华')]

In [23]:
len(xinhuashe_news)

4376

In [14]:
baseline = len(xinhuashe_news)/len(content)

In [25]:
baseline

0.8752

In [15]:
X_title = content['title'].values
y = content['is_xinhua'].values

In [61]:
content.head()

id author source                                            content  \
83661   5950     韩岩    新华社  新华社照片，巴黎，2017年6月2日\n（体育）（4）网球——法网：落日余晖\n6月1日，在...   
76118  13494     陈聪    新华社  　　新华社北京５月２６日电（记者陈聪）端午节将至，粽子是端午节必不可少的美食。国家食品药品监...   
3130   86487         参考消息网  参考消息网6月16日报道 德媒称，日本首相安倍晋三上任以来从不掩饰加强防务的决心，在本周举行...   
19917  69695           新华社  \n新华社北京4月7日新媒体专电（记者王宾）快节奏生活马不停蹄，你是否常感到无力无助？压力大...   
16406  73206    李俊东    新华社  新华社照片，乌鲁木齐，2017年4月2日\n（体育）（44）篮球——CBA总决赛第二场：新疆...   

                                                 feature  \
83661  {"type":"体育","site":"新华社","url":"http://home.x...   
76118  {"type":"行业经济","site":"新华社","url":"http://home...   
3130   {"type":"亚太新闻","site":"参考消息","commentNum":"0",...   
19917  {"type":"其它","site":"新华社","url":"http://home.x...   
16406  {"type":"体育","site":"新华社","url":"http://home.x...   

                                                  title  \
83661                     （ 体育 ） （ 4 ） 网球 — — 法网 ： 落日余晖   
76118  （ 服务 ） 食药监 总局 ： “ 三全 ” 八宝 粽 和 猪肉 粽等 ５ 批次 粽子 不 合格   
3130       德媒 ： 日本 欲 军售 东南亚 抗衡 中国   日企 却 不愿 当 “ 死亡 商人 ”   
19917                  １ ０ 年间 全球 抑郁症 患者 人数 增长 超 １ ８ ％ ！   
16406       （ 体育 ） （ 44 ） 篮球 — — CBA 总决赛 第二场 ： 新疆 迎战 广东   

                                                     url  is_xinhua  
83661  http://home.xinhua-news.com/gdsdetailxhsnew/21...          1  
76118  http://home.xinhua-news.com/gdsdetailxhsnew/21...          1  
3130   http://www.cankaoxiaoxi.com/world/20170616/212...          0  
19917  http://home.xinhua-news.com/gdsdetailxhsnew/18...          1  
16406  http://home.xinhua-news.com/gdsdetailxhsnew/17...          1

In [27]:
X_title[:10]

array(['（ 体育 ） （ 4 ） 网球 — — 法网 ： 落日余晖',
       '（ 服务 ） 食药监 总局 ： “ 三全 ” 八宝 粽 和 猪肉 粽等 ５ 批次 粽子 不 合格',
       '德媒 ： 日本 欲 军售 东南亚 抗衡 中国   日企 却 不愿 当 “ 死亡 商人 ”',
       '１ ０ 年间 全球 抑郁症 患者 人数 增长 超 １ ８ ％ ！',
       '（ 体育 ） （ 44 ） 篮球 — — CBA 总决赛 第二场 ： 新疆 迎战 广东',
       '（ 科技 ） （ 1 ） 四 新元素 取好 中文名', '# （ 社会 ） （ 4 ） 清明节 前 寄 哀思',
       '[ 8 ] （ 外代 二线 ） 网球 — — 法网 ： 穆雷 晋级',
       '（ 体育 ） （ 6 ） 足球 — — 中超 ： 重庆 当代 力帆 胜 北京 中赫 国安',
       '（ 体育 · 中超 ） 中国足协 ： 已 受理 秦升 申诉 \u3000 会 尽快 处理'], dtype=object)

In [29]:
y[:10]

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

## 2.文本表征

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=30000)
X_title = vectorizer.fit_transform(X_title)

In [17]:
X_title.shape

(5000, 10552)

## 3.划分训练集测试集

In [18]:
indices = np.arange(len(y))

In [19]:
np.random.shuffle(indices)

In [20]:
indices

array([ 273, 4672, 1636, ...,  169, 2677, 2496])

In [21]:
split_test = 0.25
train_indices = indices[int(len(indices)*split_test):]
test_indices = indices[:int(len(indices)*split_test)]

In [22]:
X_t_train,X_t_test,y_train,y_test = (X_title[train_indices],X_title[test_indices],y[train_indices],y[test_indices])

In [23]:
X_t_train

<3750x10552 sparse matrix of type '<class 'numpy.float64'>'
	with 27550 stored elements in Compressed Sparse Row format>

## 4.训练分类器并测试

In [1]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
def get_performance(clf, X_, y_):
    y_hat = clf.predict(X_.toarray())
    print('percision is: {}'.format(precision_score(y_, y_hat)))
    print('recall is: {}'.format(recall_score(y_, y_hat)))
    print('roc_auc is: {}'.format(roc_auc_score(y_, y_hat)))
    print('confusion matrix: \n{}'.format(confusion_matrix(y_, y_hat, labels=[0, 1])))

### 4.1 朴素贝叶斯分类器

In [43]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_t_train.toarray(), y_train)

GaussianNB(priors=None)

In [45]:
get_performance(clf,X_t_train,y_train)

percision is: 1.0
recall is: 0.9963381141287763
roc_auc is: 0.9981690570643882
confusion matrix: 
[[ 473    0]
 [  12 3265]]


In [46]:
get_performance(clf,X_t_test,y_test)

percision is: 0.9380692167577414
recall is: 0.9372156505914467
roc_auc is: 0.743442262381816
confusion matrix: 
[[  83   68]
 [  69 1030]]


## 4.2决策树分类器

In [47]:
from sklearn.tree import DecisionTreeClassifier
clf_tree = DecisionTreeClassifier(class_weight={0:5,1:4},criterion='entropy',max_features=5000)
clf_tree.fit(X_t_train,y_train)

DecisionTreeClassifier(class_weight={0: 5, 1: 4}, criterion='entropy',
            max_depth=None, max_features=5000, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [48]:
get_performance(clf_tree,X_t_train,y_train)

percision is: 1.0
recall is: 1.0
roc_auc is: 1.0
confusion matrix: 
[[ 473    0]
 [   0 3277]]


In [49]:
get_performance(clf_tree,X_t_test,y_test)

percision is: 0.9723018147086915
recall is: 0.9262966333030027
roc_auc is: 0.8671218265852761
confusion matrix: 
[[ 122   29]
 [  81 1018]]


In [50]:
y_hat_test = clf.predict(X_t_test.toarray()[:1000])

In [51]:
y_hat_test

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [52]:
candidate_indices = []
for index, (y,yhat) in enumerate(zip(y_test,y_hat_test)):
    if y == 0 and yhat == 1:
        candidate_indices.append(test_indices[index])

In [53]:
candidate_indices

[3803,
 1695,
 3619,
 1884,
 554,
 2117,
 2382,
 4079,
 2869,
 289,
 1063,
 1777,
 3610,
 2274,
 280,
 2914,
 3939,
 3568,
 2921,
 2165,
 1159,
 1293,
 3185,
 4260,
 2763,
 2213,
 4279,
 4500,
 4017,
 4203,
 3934,
 186,
 2232,
 2939,
 2129,
 1931,
 1508,
 2255,
 4473,
 3094,
 2623,
 3834,
 1875,
 4178,
 2559,
 4505,
 4711,
 1151,
 2439,
 1523,
 4233,
 3071,
 508]

In [54]:
content.iloc[508]['content']

'????□本报记者刘向东本报通讯员杨春旺刘超\r\n????燠热天有了一场淅淅沥沥的雨。在内黄县马上乡燕庄村的一个养猪场内，54岁的吴明彦收到了多年前资助过的一个女大学生发来的微信红包和一条短信：吴姨，你想不想当姥姥？\r\n????吴明彦高兴，拿着手机让丈夫燕志学看。老燕也开心地笑了，“这些孩子都知道感恩，咱这些年的付出值了！”\r\n????一\r\n????乡里多“能人”，59岁的老燕算一个：他17岁当生产队会计，还有照相手艺，背着海鸥120相机走村串巷，糊口不是问题。不过，照相不是他的理想，他想上大学。但小儿麻痹落下的残疾让他痛失机会。\r\n????家在四川资阳、长相水灵的吴明彦1984年随表姐来中原“找婆家”时，只见一面，就喜欢上了燕志学。成了夫妻，吴明彦跟燕志学学会了全套照相技术。日久天长，夫妻俩分工明确：老燕照相，吴明彦洗影。\r\n????燕志学要经常吃药，还藏私房钱——吴彦明一早就知道，但从不说破，“他那钱孝敬他爹妈了”；偶尔还有埋怨：“你跟我说说又咋了？我能不让你管父母？”他的父母都是八十多岁的老人了，健在。\r\n????1993年，他们养了一群鸡，最多时500多只；2003年，他们又改行养了猪，最多时年出栏上千头肉猪。\r\n????生活一天天富裕，老燕夫妇也成了村民眼里名副其实的“能人”。\r\n????二\r\n????能人有烦恼，也有刻骨铭心的疼。按照老燕夫妇的说法，他们的小儿子也能成为“能人”的。\r\n????老燕举了个例子：小儿子上初三时，有天傍晚放学回家的路上看到有个老者艰难地拉着一架子车麦秸，二话不说把自行车扔到麦秸上，拉起架子车把老者送回家后，汗水淋漓摸黑回到家。老燕问他自行车呢，小儿子一拍额头，忘架子车上了。“这孩子打小就热心肠。”老燕说。\r\n????2005年，大儿子结婚。小儿子给哥哥帮忙盖房时出了意外，花季少年的17岁成了定格。\r\n????老燕像得了精神病一样，半夜里起来在外面转来转去。有一天，老燕转回来搡醒了吴明彦说，咱给老二准备的结婚钱还得为老二花了。他打小喜欢做好事，咱给他准备的那些钱，干脆就替他做些好事儿吧。\r\n????“我们一家人心都可善。”吴明彦说，有一年，她从电视里看到鹤壁一个小女孩因白血病被家人遗弃，她哭了一场，第二天就上邮局寄去了一笔钱……\r\n????三\r\n????因为照过相，

In [55]:
content.iloc[508]['source']

'河南日报第14版'

## 4.3 KNN分类器

In [26]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=5)
clf_knn.fit(X_t_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [27]:
get_performance(clf_knn,X_t_train,y_train)

percision is: 1.0
recall is: 0.9474643182508351
roc_auc is: 0.9737321591254176
confusion matrix: 
[[ 457    0]
 [ 173 3120]]


In [30]:
get_performance(clf_knn,X_t_test,y_test)

percision is: 0.9424326833797586
recall is: 0.9235668789808917
roc_auc is: 0.7564854262454127
confusion matrix: 
[[  89   62]
 [  84 1015]]


In [31]:
y_hat_test = clf_knn.predict(X_t_test.toarray()[:1000])

In [36]:
y_hat_test[:100]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [37]:
candidate_indices = []
for index, (y,yhat) in enumerate(zip(y_test,y_hat_test)):
    if y == 1 and yhat == 1:
        candidate_indices.append(test_indices[index])

In [38]:
len(candidate_indices)

810

In [39]:
candidate_indices[:10]

[273, 4672, 1636, 244, 3234, 1764, 1938, 4441, 782, 2824]

In [41]:
content.iloc[273]['content']

'新华社照片，外代，2017年5月15日\\n（外代二线）2017美国小姐选美比赛\\n5月14日，美国小姐选美比赛在美国内华达州的拉斯维加斯举行。\\n新华社/路透'

In [42]:
content.iloc[273]['source']

'新华社'

## 4.4 SVM分类器

In [48]:
from sklearn.svm import SVC
clf_svm = SVC(gamma='auto',kernel='linear')
clf_svm.fit(X_t_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [49]:
get_performance(clf_svm,X_t_train,y_train)

percision is: 0.9945635759589248
recall is: 1.0
roc_auc is: 0.9803063457330417
confusion matrix: 
[[ 439   18]
 [   0 3293]]


In [51]:
get_performance(clf_svm,X_t_test,y_test)

percision is: 0.9137353433835846
recall is: 0.9927206551410374
roc_auc is: 0.655300724921512
confusion matrix: 
[[  48  103]
 [   8 1091]]


In [56]:
y_hat_test = clf_svm.predict(X_t_test.toarray())

In [57]:
y_hat_test[:100]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## 4.5 随机森林分类器

In [75]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=10552,n_informative=2, n_redundant=0,random_state=0, shuffle=False)
clf_rf = RandomForestClassifier(n_estimators=100,criterion='entropy',max_depth=10,random_state=0)
clf_rf.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [76]:
get_performance(clf_rf,X_t_train,y_train)

percision is: 0.8781333333333333
recall is: 1.0
roc_auc is: 0.5
confusion matrix: 
[[   0  457]
 [   0 3293]]


In [71]:
get_performance(clf_rf,X_t_test,y_test)

percision is: 0.8792
recall is: 1.0
roc_auc is: 0.5
confusion matrix: 
[[   0  151]
 [   0 1099]]


## 4.6 XGBoost分类器

In [78]:
from xgboost import XGBClassifier
xgbc = XGBClassifier()
xgbc.fit(X_t_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [79]:
get_performance(xgbc,X_t_train,y_train)

percision is: 0.8781333333333333
recall is: 1.0
roc_auc is: 0.5
confusion matrix: 
[[   0  457]
 [   0 3293]]


E:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [80]:
get_performance(xgbc,X_t_test,y_test)

percision is: 0.8792
recall is: 1.0
roc_auc is: 0.5
confusion matrix: 
[[   0  151]
 [   0 1099]]


E:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


## 4.7 K-means聚类

In [81]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2, random_state=0).fit(X_t_train)

In [86]:
set(kmeans.labels_)

{0, 1}

In [83]:
get_performance(kmeans,X_t_train,y_train)

percision is: 0.8406555090655509
recall is: 0.7321591254175523
roc_auc is: 0.3660795627087762
confusion matrix: 
[[   0  457]
 [ 882 2411]]


In [84]:
get_performance(kmeans,X_t_test,y_test)

percision is: 0.8444902162718847
recall is: 0.7461328480436761
roc_auc is: 0.37306642402183804
confusion matrix: 
[[  0 151]
 [279 820]]


## 5.模型保存及再次使用

In [56]:
import pickle

In [57]:
with open('clf', 'wb') as picklefile:  
    pickle.dump(clf,picklefile)

In [58]:
with open('clf', 'rb') as training_model:  
    model = pickle.load(training_model)

In [59]:
y_hat_test = model.predict(X_t_test.toarray()[:1000])

In [60]:
y_hat_test

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

## 注：文本分类的一般步骤：https://stackabuse.com/text-classification-with-python-and-scikit-learn/